### ISSUE TITLE
Título incorrecto en login

### ISSUE THREAD

**Issue by eperezf** [eperezf/NVIO#1]
El título de la página de Login tiene la sección "NVIO |" duplicada.

<img width="229" alt="Screen Shot 2020-08-01 at 00 14 11" src="https://user-images.githubusercontent.com/6854338/89093888-1b973d00-d38c-11ea-9745-d2bfcbcebf78.png">

**Comment by GonzoVF** [comment]
Ya está arreglado en el branch que estoy trabajando, tiene que ver con como se pasan los títulos
![image](https://user-images.githubusercontent.com/31936697/89104840-4b752d80-d3ea-11ea-80db-3b94b3eabe55.png)

Ahora en la definición de ruta se pasa el nombre de la página y el header lo concatena para el display
![image](https://user-images.githubusercontent.com/31936697/89104874-7fe8e980-d3ea-11ea-8c25-89dc277f9f8c.png)
![image](https://user-images.githubusercontent.com/31936697/89104880-89725180-d3ea-11ea-92ce-9654341334a5.png)

Cuando feature/user-content esté completo y se integre a develop no va a ser un problema
