### ISSUE TITLE
Inicio de página gigante luego de hacer un envío

### ISSUE THREAD

**Issue by piamoreau** [eperezf/NVIO#10]
**Describe the bug**
cuando se completa e formulario para hacer un pedido, muestra la pestaña historial pedidos pero con un inicio de página muy grande, de hecho en la esquina superior izquierda aparece cerrar sesión pero es casi inapreciable

**To Reproduce**
1.nuevo envío
2. rellenar formulario
3. enviar

**Expected behavior**
debería mostrar la barra lateral de siempre y en caso de ser diferente, mostrar una barra superior pero del mismo ancho que la inicial con la opción de desplegar las otras opciones

**Screenshots**
![image](https://user-images.githubusercontent.com/50148991/89721729-29ae1480-d9af-11ea-86d5-61837c04714b.png)
![image](https://user-images.githubusercontent.com/50148991/89721731-2d419b80-d9af-11ea-8491-892a8beb1587.png)

**Comment by eperezf** [comment]
No se ha logrado replicar el problema. Quedará fuera de v0.1.0-rc.2.

**Comment by piamoreau** [comment]
Tampoco me pasa ahora :(
