### ISSUE TITLE
MEJORA: mi perfil ---> logo empresa

### ISSUE THREAD

**Issue by piamoreau** [eperezf/NVIO#13]
**Mejora**
en la pestaña "mi perfil" el logo de la empresa debería ir centrado y cuando se edite podría mostrar de inmediato el cambio y no esperar guardarlos

**To Reproduce**
1. mi perfil
2. editar perfil

![image](https://user-images.githubusercontent.com/50148991/89721855-75ad8900-d9b0-11ea-9ce7-81a37cd22420.png)

**Comment by eperezf** [comment]
Enhancement quedará para otro release. No es vital para el MVP @piamoreau.

Quedará abierto de todas maneras para tener registro.
