### ISSUE TITLE
MEJORA: botones del color del logo (magenta)

### ISSUE THREAD

**Issue by piamoreau** [eperezf/NVIO#14]
**Mejora**
todos (o por lo menos los azules) los botones en la plataforma podrían tener el mismo color del logo en vez de azul 
color: #F859D7

![image](https://user-images.githubusercontent.com/50148991/89721971-6713a180-d9b1-11ea-82ae-8bcfe4b75789.png)

**Comment by GonzoVF** [comment]
Siento que sobrecargaría usar ese mismo color con todo, pero quizá verde para contraste
