### ISSUE TITLE
Franja de espacio, zoom y deslizado horizontal en vista móvil

### ISSUE THREAD

**Issue by eperezf** [eperezf/NVIO#17]
**Describe the bug**
En la vista móvil es posible hacer zoom, deslizar de forma horizontal y existe una franja de espacio blanco a la derecha.

**To Reproduce**
1. Ir al sitio en un dispositivo móvil
2. Intentar deslizar hacia los lados
3. intentar hacer zoom

**Expected behavior**
La versión móvil no debería permitir zoom ni desplazamiento horizontal (se debería comportar como una app). Además se debería eliminar la franja lateral.

**Screenshots**
![IMG_0312](https://user-images.githubusercontent.com/6854338/89845282-0bc9e680-db4c-11ea-9dc7-a31c91b7d9e6.PNG)
![IMG_0314](https://user-images.githubusercontent.com/6854338/89845318-1f754d00-db4c-11ea-9590-23cc5252546c.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 13.6
 - Browser: Chrome 
 - Version 84.0.4147.71

**Additional context**
Revisar` <meta name="viewport">` en `<head>`

**Comment by eperezf** [comment]
Issue todavía presente en release más reciente.

**Comment by GonzoVF** [comment]
Arreglado nuevamente en 407d5be2f0b7adbded56785d063564e6f44aec12
