### ISSUE TITLE
Fix scroll lateral vista "Quienes somos"

### ISSUE THREAD

**Issue by Xmax2997** [eperezf/NVIO#18]
**Describe the enhancement you want**
En la vista "Quienes somos" se debe eliminar el scroll lateral existente.

**Describe the solution you'd like**
Que se vea igual que las demas vistas del landing page, es decir, que la página sea fija en el sentido horizontal.

Screenshot
![image](https://user-images.githubusercontent.com/42940482/89851470-81d54a00-db5a-11ea-85da-ea2c4fa082e9.png)

**Additional context**

Windows 10 
Chrome

**Comment by eperezf** [comment]
Duplicado de #17. Utilizar ese como principal.
