### ISSUE TITLE
Crash con credenciales particulares

### ISSUE THREAD

**Issue by GonzoVF** [eperezf/NVIO#19]
**Describe the bug**
Problemas al cargar la página con credenciales específicas, no es reproducible con otra cuenta.

**To Reproduce**
1. Login con credenciales indicadas en el screenshot
2. Click en Mi Perfil
3. Click en Nuevo Envío
4. Error

**Expected behavior**

**Screenshots**
![Dash Error](https://user-images.githubusercontent.com/31936697/89931289-f6030280-dbd9-11ea-9fb0-794141337783.jpg)
![image](https://user-images.githubusercontent.com/31936697/89931671-82adc080-dbda-11ea-9c62-87d256f21a85.png)

**Desktop**
 - OS: Microsoft Windows 10 v1909
 - Browser: Firefox Browser
 - Version 79.0 (64-bit)

**Additional context**

**Comment by eperezf** [comment]
El error es porque la empresa no tiene una dirección de remitente creada. Esto se puede replicar cuando se creen nuevos usuarios por lo que es importante arreglarla igual.
