### ISSUE TITLE
Orden de fecha de creación no distingue dentro del mismo día

### ISSUE THREAD

**Issue by eperezf** [eperezf/NVIO#20]
**Describe the bug**
Cuando pido ordenar por fecha en el historial de pedidos, los pedidos que están en la misma fecha no están ordenados por la hora de creación.

**To Reproduce**
1. Ir a historial de pedidos
2. Click en "fecha de creación" para ordenar por fecha
3. Ver pedidos en la misma fecha
4. Los pedidos en una misma fecha no están ordenados

**Expected behavior**
Los pedidos creados dentro de una misma fecha deben estar ordenados de la misma manera

**Screenshots**
<img width="1300" alt="Screen Shot 2020-08-11 at 17 33 44" src="https://user-images.githubusercontent.com/6854338/89951249-12fafe00-dbf9-11ea-8aa4-db3dc3439f8c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 84.0.4147.105

**Additional context**
La variable es un Unix Epoch. Quizás se puede ordenar y luego convertir la variable.

**Comment by GonzoVF** [comment]
El servicio que utilizamos para ordenar los datos es https://datatables.net/ (en caso de que alguien quiera meterle manos antes que yo). En todo caso, voy a empezar a revisar eso hoy y entiendo como debería ser la comparación, es cosa de buscar la sintaxis correcta en la documentación y agregarla al script que declara la tabla.
