### ISSUE TITLE
Apartado casa, condominio, departamento está oculto

### ISSUE THREAD

**Issue by Xmax2997** [eperezf/NVIO#21]
**Describe the bug**
No se muestra apartado casa, condominio, departamentos en la vista "mi perfil"

**To Reproduce**
1. Ir a mi perfil
2. En editar perfil asegurarse de que existan datos en el apartado "casa, condomino, departamento"
3. Guardar los cambios
4. Ver que no se muestran.

**Expected behavior**
Poder ver los datos del apartado si existen
**Screenshots**
![image](https://user-images.githubusercontent.com/42940482/90150398-9e88a200-dd53-11ea-8bbd-bb3f3e413d4c.png)
![image](https://user-images.githubusercontent.com/42940482/90150448-acd6be00-dd53-11ea-922e-30fcadc1c009.png)

**Comment by eperezf** [comment]
Esto es problema de backend también, si no me equivoco.
