### ISSUE TITLE
No se pueden ingresar envíos

### ISSUE THREAD

**Issue by piamoreau** [eperezf/NVIO#23]
**Describe the bug**
Al ingresar una solicitud de envío (aunque esté correcta) este no se guarda y la página se refresca

**To Reproduce**
1. nuevo envío
2. completar correctamente
3. enviar

**Expected behavior**
el pedido debería ser enviado y guardado en la base de datos de historial de pedidos

**Comment by eperezf** [comment]
@piamoreau por favor indicar los datos que utilizaste al ingresar (puede ser por interno para mantener privacidad).

**Comment by eperezf** [comment]
Issue invalidado.
