### ISSUE TITLE
Cambios en el resumen de pedidos del dashboard

### ISSUE THREAD

**Issue by Xmax2997** [eperezf/NVIO#26]
**Describe the enhancement you want**
Incluir campo de nombre del destinatario, botón para ver detalles del pedido y acceso directo al historial de pedidos.

**Describe the solution you'd like**
Poder ver fácilmente el nombre del destinatario del pedido, poder acceder a los detalles del pedido fácilmente e incluir un botón de acceso rápido al historial de pedidos
**Describe alternatives you've considered**

**Additional context**

**Comment by GonzoVF** [comment]
Este es un tema de frontend, creo que ya recibo toda la info necesaria de backend

**Comment by GonzoVF** [comment]
@eperezf voy a hacer un push con la funcionalidad casi completa en un momento, es necesario recibir el ID de usuario para proporcionar tracking desde ahí mismo y para eso te necesito a tí
