### ISSUE TITLE
Orden de tabla de costos de envío 

### ISSUE THREAD

**Issue by Xmax2997** [eperezf/NVIO#30]
**Describe the enhancement you want**
El orden de la tabla de costos de envío en el dashboard debe ser alfabético utilizando el campo de destino.

**Comment by Xmax2997** [comment]
No arreglado

**Comment by piamoreau** [comment]
tabla de costos no de pedidos

**Comment by GonzoVF** [comment]
> 
> 
> No arreglado

Ahora si
