### ISSUE TITLE
Validación de items no existentes

### ISSUE THREAD

**Issue by eperezf** [eperezf/NVIO#32]
**Describe the bug**
Con una cuenta nueva, al momento de intentar crear un nuevo envío el sistema intenta validar los atributos `firstName.S` y `lastName.S` en el archivo `dash.js` que ya están depreciados y no se utilizan. Se deben eliminar en el próximo sprint. Por mientras quedarán comentadas las líneas en producción para evitar el exceso de hotfix.

**To Reproduce**
1. Tener cuenta nueva
2. Rellenar datos de usuario
3. Ir a nuevo envío
4. Sitio se cae

**Expected behavior**
Se debería poder crear un nuevo envío sin problemas.

**Comment by Xmax2997** [comment]
Ya no sucede lo descrito, arreglado
