### ISSUE TITLE
Correos sensibles a mayúsculas

### ISSUE THREAD

**Issue by eperezf** [eperezf/NVIO#33]
**Describe the bug**
Los correos de inicio de sesión son sensibles a mayúsculas, lo cual no debería pasar.

**To Reproduce**
1. Ir a login
2. Ingresar un correo válido pero con alguna letra mayúscula
3. Ingresar contraseña
4. Poner Login
5. El sistema no ingresa

**Expected behavior**
Los correos no deberían distinguir de mayúsculas y minúsculas.

**Comment by Xmax2997** [comment]
Funciona correctamente
