### ISSUE TITLE
Sistema no guarda el correo de destinatario en nueva orden

### ISSUE THREAD

**Issue by eperezf** [eperezf/NVIO#34]
**Describe the bug**
El sistema no guarda el correo de destinatario al crear una nueva orden. Esto solo se ve reflejado en el log al ingresar la orden. El dato tampoco se usa para nada por ahora por lo que no es crítico. Además, la variable se llama `companyEmail`, cuando debería ser algo como `destEmail`.

**To Reproduce**
1. Ir a nueva orden
2. Crear nuevo pedido
3. El problema se ve en la base de datos

**Expected behavior**
El sistema debería guardar el correo en un atributo en la base de datos con el nombre correcto.

**Comment by Xmax2997** [comment]
El sistema ahora presenta el comportamiento esperado, arreglado
