### ISSUE TITLE
Sort incorrecto con comuna Ñuñoa

### ISSUE THREAD

**Issue by eperezf** [eperezf/NVIO#35]
**Describe the bug**
Cuando se elige Ñuñoa como una comuna y una posterior (P en adelante), el sistema no ordena de forma correcta las comunas para obtener el costo.
**To Reproduce**
1. Ir a nuevo envío
2. Click en dropdown de comuna de origen
3. Elegir Ñuñoa
4. Click en dropdown de comuna de destino
5. Elegir cualquier comuna posterior a Pedro Aguirre Cerda
6. El sistema se cae porque no encuentra la pareja.

**Expected behavior**
Debería considera la Ñ como después de la N, permitiendo ordenar con letras posteriores

**Screenshots**

**Additional context**
Modificar la línea 16 de `static/js/update-cost.js` a `localities.sort((a, b) => a.localeCompare(b, 'es', {sensitivity: 'base'}))`

**Comment by eperezf** [comment]
También modificar la línea 380 de `routes/dash.js` a `localities.sort((a, b) => a.localeCompare(b, 'es', {sensitivity: 'base'}))`

**Comment by Xmax2997** [comment]
![image](https://user-images.githubusercontent.com/42940482/92294420-1cc30900-eefa-11ea-95a0-48b70812e013.png)


Funciona correctamente
