### ISSUE TITLE
Aceptar caracteres especiales en nombre legal y de fantasía

### ISSUE THREAD

**Issue by Xmax2997** [eperezf/NVIO#36]
**Describe the bug**
El campo nombre legal y de fantasía no acepta caracteres especiales. Algunas empresas los utilizan.
Ej: "Soluciones tecnológicas A&M SpA"

**To Reproduce**
1. Go to Mi perfil
2. Click on 'Editar perfil'
3. Ingresar un caracter especial en el campo nombre legal o nombre fantasía 

**Expected behavior**
Aceptar caracteres especiales

**Screenshots**
![image](https://user-images.githubusercontent.com/42940482/92289006-f347b480-eedc-11ea-906c-c4b10177030a.png)
![image](https://user-images.githubusercontent.com/42940482/92289025-fe024980-eedc-11ea-9794-3849372713d4.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chromei]

**Comment by eperezf** [comment]
@GonzoVF has tu magia de regex pls

**Comment by GonzoVF** [comment]
> 
> 
> @GonzoVF has tu magia de regex pls

Aye aye my Cap'n

**Comment by Xmax2997** [comment]
Funciona correctamente
