### ISSUE TITLE
Error al subir logo al perfil

### ISSUE THREAD

**Issue by Xmax2997** [eperezf/NVIO#41]
**Describe the bug**
Hay un error al subir el logo al perfil

**To Reproduce**
1. Go to Editar perfil
2. Click on subir archivo
3. Seleccionar un archivol .png y subirlo
4. Guardar perfil
5. Ver el error (no aparece el logo)

**Expected behavior**
Que se suba y visualice correctamente

**Screenshots**

![image](https://user-images.githubusercontent.com/42940482/92293805-614ba600-eef4-11ea-8d94-0bfdd032c71c.png)
![image](https://user-images.githubusercontent.com/42940482/92293813-6ad50e00-eef4-11ea-8c43-cadc6621c54b.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]

**Comment by Xmax2997** [comment]
![image](https://user-images.githubusercontent.com/42940482/92295087-36188500-eefb-11ea-98a3-adff29d74345.png)
![image](https://user-images.githubusercontent.com/42940482/92295110-3add3900-eefb-11ea-9cd1-9b9d4e05db72.png)
![image](https://user-images.githubusercontent.com/42940482/92295136-416bb080-eefb-11ea-98d9-a0d16d596432.png)

Sigue presentandose el mismo error

**Comment by eperezf** [comment]
Saldrá en RC2
