### ISSUE TITLE
Todos los detalles de pedido en dashboard muestran el mismo pedido

### ISSUE THREAD

**Issue by eperezf** [eperezf/NVIO#42]
**Describe the bug**
Al hacer click en detalle en uno de los últimos 5 pedidos, el modal muestra solamente el más reciente, independiente del botón de detalle que se presione

**To Reproduce**
1. iniciar sesión
2. Click en cualquier botón de detalle de pedido
3. Detalle no calza con pedido solicitado

**Expected behavior**
Cada botón de detalle debe mostrar el detalle de la orden respectiva, no el detalle de la más reciente

**Additional context**
OJO: Esto también afecta al botón de cancelar pedido. Es bastante importante arreglarlo asap.

**Comment by GonzoVF** [comment]
On it
