### ISSUE TITLE
Mantener sesión iniciada

### ISSUE THREAD

**Issue by piamoreau** [eperezf/NVIO#8]
**Describe the bug**
no mantiene la sesión iniciada

**To Reproduce**
1. inicio
2. iniciar sesión

**Expected behavior**
debería mantener la sesión iniciada

**Screenshots**
![image](https://user-images.githubusercontent.com/50148991/89721331-527fdb00-d9aa-11ea-82fc-629e2b00cd3c.png)

**Comment by eperezf** [comment]
Este comportamiento es esperado para este sprint.
